apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: webserver
    name: webserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webserver
      name: webserver
  template:
    metadata:
      labels:
        app: webserver
        name: webserver
    spec:
      containers:
      - name: apache
        image: fedora/apache
        ports:
        - containerPort: 80